title: Ishwar Kapoor
theme: minima

nav:
  - title: Intro
    url: /
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/

google_verification: "googlec1ec095a28697887"

plugins:
  - jekyll-sitemap
